gui:
  # Catppuccin macchiato theme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6da95" # Green
      - bold
    inactiveBorderColor:
      - "#cad3f5" # Text
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    selectedRangeBgColor:
      - "#363a4f" # Surface0
    cherryPickedCommitBgColor:
      - "#8bd5ca" # Teal
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    unstagedChangesColor:
      - "#ed8796" # Red
  # Catppuccin mocha theme
#  theme:
#    lightTheme: false
#    activeBorderColor:
#      - "#a6e3a1" # Green
#      - bold
#    inactiveBorderColor:
#      - "#cdd6f4" # Text
#    optionsTextColor:
#      - "#89b4fa" # Blue
#    selectedLineBgColor:
#      - "#313244" # Surface0
#    selectedRangeBgColor:
#      - "#313244" # Surface0
#    cherryPickedCommitBgColor:
#      - "#94e2d5" # Teal
#    cherryPickedCommitFgColor:
#      - "#89b4fa" # Blue
#    unstagedChangesColor:
#      - "#f38ba8" # Red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
